### ISSUE TITLE
Very slow on Windows

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#115]
I noticed that localtileserver is very slow on Windows. It took ~13 seconds to generate tiles for [this ](https://github.com/giswqs/data/raw/main/raster/srtm90.tif)very small GeoTIFF (14 MB). It used to be very fast on Linux. I am not sure what causes the issue. 

![Animation](https://user-images.githubusercontent.com/5016453/182700120-9839570e-8db9-40a0-b608-a116f29ecc71.gif)

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

# First, create a tile server from local raster file
client = TileClient('srtm90.tif')

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(client)

m = Map(center=client.center(), zoom=client.default_zoom)
m.add_layer(t)
m
```

env
```text
--------------------------------------------------------------------------------
  Date: Wed Aug 03 16:17:46 2022 Eastern Daylight Time

                     OS : Windows
                 CPU(s) : 16
                Machine : AMD64
           Architecture : 64bit
                    RAM : 31.7 GiB
            Environment : Jupyter

  Python 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC
  v.1916 64 bit (AMD64)]

        localtileserver : 0.5.11
                  flask : 2.1.3
          flask_caching : 1.10.1
             flask_cors : 3.0.10
            flask_restx : 0.5.1
               requests : 2.28.1
               werkzeug : 2.1.2
                  click : 8.1.3
          server_thread : 0.2.0
                 scooby : 0.5.12
            large_image : 1.15.1
large_image_source_gdal : 1.15.1
             cachetools : 4.2.4
                    PIL : 9.2.0
                 psutil : 5.9.1
                  numpy : 1.23.1
             palettable : 3.3.0
                 pyproj : 3.3.1
             osgeo.gdal : 3.4.2
             ipyleaflet : 0.17.0
             jupyterlab : 3.4.4
              traitlets : 5.3.0
                shapely : 1.8.2
                 folium : 0.12.1.post1
             matplotlib : 3.5.2
--------------------------------------------------------------------------------
```

**Comment by giswqs** [comment]
For reference, using the localtileserver binder, it takes less than two seconds to generate tiles.

**Comment by giswqs** [comment]
I also noticed that the spinning wheel is staying a bit longer than it should be. It can be a bit annoying to keep seeing the spinning wheel. Can it be turned off?

![Animation](https://user-images.githubusercontent.com/5016453/182707080-42600529-a7f5-4093-b883-df0cf281bac5.gif)

**Comment by banesullivan** [comment]
> I also noticed that the spinning wheel is staying a bit longer than it should be. It can be a bit annoying to keep seeing the spinning wheel. Can it be turned off?

I added this recently -- I'd like to keep it as I think it is valuable and it does accurately correspond to tiles loading. To disable it, simply pass `show_loading=False` when calling `get_leaflet_tile_layer()` or set that property on the `leaflet.TileLayer`: https://ipyleaflet.readthedocs.io/en/latest/layers/tile_layer.html#ipyleaflet.leaflet.TileLayer.show_loading

**Comment by banesullivan** [comment]
> I noticed that localtileserver is very slow on Windows

I'll try to look into this when I have a chance. Timing the full execution of that script isn't very insightful, so I'll have to dig into each part of the script what's taking so long. Is it the `import` that takes a while or is it opening the raster, or what?... this will require more investigative work.

Further, how Python is running on the host windows machine can significantly impact performance, such as if it is running under the linux subsystem.

**Comment by banesullivan** [comment]
My windows machine is happy today, so I'm looking into this. I've at least narrowed it down to the `get_leaflet_tile_layer()` for the most part (ipyleaflet rendering the tiles also takes a few seconds).

Collecting the metadata for this raster seems to be the culprit and specifically when it's down through the rest interface. 

I have a feeling there are a few things that need to be optimized and this will require me to really dig into this. To be honest, Windows is a pain for me to work on and I can't promise I'll get to this anytime soon

**Comment by banesullivan** [comment]
What I may do is change the implementation a bit under the hood to generally optimize the `TileClient` methods (regardless of OS) as I've been wanting to but again, this is something I can't give a timeline on as this is a fun little hobby project. It will likely come after/during #108

**Comment by banesullivan** [comment]
I've done most of the refactoring/optimization that I wanted to and this doesn't seem actionable any further. I'm hoping that whatever issue you were having have magically resolved themselves by switching to using rasterio instead of GDAL

**Comment by halieute** [comment]
Hello, good evening.

I would like to request help regarding an issue I've been facing since last week. I'm trying to use the following code to load raster data from both local files and URLs:

```python
def add_raster(self, filepath, **kwargs):
    from localtileserver import get_leaflet_tile_layer, TileClient

    client = TileClient(filepath)
    tile_layer = get_leaflet_tile_layer(client, **kwargs)

    self.add(tile_layer)
    self.center = client.center()
    self.zoom = client.default_zoom

```

However, I am encountering some difficulties and would really appreciate any guidance or suggestions you can provide.

Thank you in advance for your support!

![Image](https://github.com/user-attachments/assets/2f75043d-1c7c-4a3a-8045-b1f46526dbc2)
![Image](https://github.com/user-attachments/assets/bc0cb805-5966-418c-b85b-24d09dbd7ae9)
![Image](https://github.com/user-attachments/assets/d903f933-b2d6-4d02-8beb-4cb50f372544)
