### ISSUE TITLE
Consider changing name to `localtileserver`

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/localtileserver#12]
I'm considering changing the name to `localtileserver` all around. I.e., the repository, pip package, and import name would all be `localtileserver`.  I think this name captures the intent of this package better than `flask-tileserver`.

I'm going to mull this over for a bit.

Thoughts @giswqs since I think you might be the only downstream user thus far?

Blocks #6

**Comment by banesullivan** [comment]
Furthermore, I think the existence of [this package](https://pypi.org/project/tileserver/) with the name `tileserver` and the fact that the import name of this project is `tileserver` will lead to installation issues for many users

**Comment by giswqs** [comment]
Sounds good to me. I have not incorporated it into geemap/leafmap yet, so the name change would not affect me

**Comment by giswqs** [comment]
Nice animation. How did you create this?


![image](https://raw.githubusercontent.com/banesullivan/localtileserver/main/imgs/tile-diagram.gif)

**Comment by banesullivan** [comment]
I made it with PyVista! I will add the script to the repo for reproducibility  

https://github.com/pyvista/pyvista
