### ISSUE TITLE
Extract roi issue

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#124]
I was testing the `extract_roi()` function using the sample `bahamas_rgb.tif`. It seems the extracted image does not match the bounding box. Is this a bug?

```python
client.extract_roi(-77.9425, -77.4701, 23.8959, 24.2019)
```
![image](https://user-images.githubusercontent.com/5016453/199383881-93797d57-973a-4bb2-9e23-88592c5da402.png)

![image](https://user-images.githubusercontent.com/5016453/199384002-d37ebe49-8ac8-4186-85c8-9c7d88d15cf8.png)

**Comment by banesullivan** [comment]
odd. I think this is a simple projection issue. I will investigate

**Comment by banesullivan** [comment]
This should be fixed but I'll need a bit to get a release out
