### ISSUE TITLE
Support for Amazon SageMaker Studio Lab

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#128]
[Amazon SageMaker Studio](https://studiolab.sagemaker.aws/) is a free cloud computing platform, similar to Binder but users can install packages and save files permanently. It seems localtileserver is not working on SageMaker, even after running the following code. Any advice?

```python
import os
os.environ["LOCALTILESERVER_CLIENT_PREFIX"] = "proxy/{port}"
```

![image](https://user-images.githubusercontent.com/5016453/202193490-3549c6f6-4de7-47df-b109-ef7f9cc7fecb.png)

![image](https://user-images.githubusercontent.com/5016453/202194298-a7b659a5-4c0c-45ca-8ed9-a075d61a335e.png)

![image](https://user-images.githubusercontent.com/5016453/202195161-386d7701-5901-4cca-a6d5-0922f291c681.png)

![image](https://user-images.githubusercontent.com/5016453/202193569-d5575399-193d-4ac3-ae85-5b3e30e954f1.png)

**Comment by banesullivan** [comment]
I haven't used sage maker yet but it seems to be gaining a lot of traction... I'll see what I can do to get this to work.

**Comment by banesullivan** [comment]
I have no idea where to begin with this... I signed up for a handful of different "SageMaker" things and could not figure out how to launch a notebook environment anywhere... this whole has left me quite confused.

Anywho, I think "SageMaker Studio Lab" is the platform? right? If so, I'm waitlisted:

<img width="722" alt="Screen Shot 2023-01-29 at 8 04 03 PM" src="https://user-images.githubusercontent.com/22067021/215378774-8d96dc1f-1161-42d9-86ec-233ccaa7e1ca.png">

**Comment by giswqs** [comment]
@banesullivan Yes, SageMaker Studio Lab is the free version, something similar to Google Colab. It might take a few hours /days to get the account approved. Other SageMaker products are not free.

**Comment by banesullivan** [comment]
I finally have an account, but I'm having trouble getting `ipywidgets` to work at all... tried restarting JupyterLab from the sagemaker menu but no luck...

**Comment by banesullivan** [comment]
However, from the looks of it. SageMaker truly is just JupyterLab (unlike Google Colab) so setting up Jupyter-server-proxy to get this working should be all the same

**Comment by giswqs** [comment]
Yes, ipyleaflet might not work with SageMaker Studio. Try folium

**Comment by banesullivan** [comment]
Indeed, same set up with JupyterLab, just need the right prefix. This works as:

```py
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = f"studiolab/default/jupyter/proxy/{{port}}"
```

<img width="1179" alt="Screen Shot 2023-02-06 at 2 18 33 PM" src="https://user-images.githubusercontent.com/22067021/217090234-2dc70bc5-f1e3-4aa7-994f-9605f39f38ec.png">

-----

On MyBinder, this prefix is easy to get with the `JUPYTERHUB_SERVICE_PREFIX` environment variable. Unfortunately, I do not see anything like this in the environment on sagemaker.... though `studiolab/default/jupyter/` seems standard enough that this is probably the prefix in any environment -- @giswqs, you might know better than I

**Comment by banesullivan** [comment]
Really IMO, we should raise issues like this upstream in jupyter-server-proxy and see if they can make this easier to do in Colab, SageMaker, MyBinder, etc.

**Comment by banesullivan** [comment]
I'll add it to my to do list to open an issue upstream outlining the need clearly

**Comment by giswqs** [comment]
That's fantastic! How did you figure out the prefix?

**Comment by giswqs** [comment]
Is it possible to get the browser URL programmatically and extract the prefix from the URL?

**Comment by banesullivan** [comment]
I think @arttt was able to do this. See https://github.com/banesullivan/localtileserver/issues/101#issuecomment-1397932114
