### ISSUE TITLE
Displaying images on remote JupyterHub

### ISSUE THREAD

**Issue by Dodekaphonia** [banesullivan/localtileserver#134]
Hi!
Following up [#29](https://github.com/banesullivan/localtileserver/issues/29), [#66](https://github.com/banesullivan/localtileserver/issues/66), [#72](https://github.com/banesullivan/localtileserver/issues/72). I'm trying to use localtileserver for displaying image with folium on remote Jupyter Hub (physical server) and the image is not showing. As far as I understand, instead of TileClient function I need to use  RemoteTileClient.
I've tried already:
```
RemoteTileClient('image.tif', host = 'http://127.0.0.1:port',  default_projection='EPSG:3031')
RemoteTileClient('image.tif', host = 'http://127.0.0.1', default_projection='EPSG:3031')
RemoteTileClient('image.tif', host = 'http:/user/username/', default_projection='EPSG:3031')
```

hostname (http://127.0.0.1) and port were received with 
```
from notebook import notebookapp
servers = list(notebookapp.list_running_servers())
print(servers)
```

So my question is what is the correct way to pass host and port to  RemoteTileClient function? Or am I missing something?

For remote JupyterHub I followed this instruction: https://localtileserver.banesullivan.com/installation/remote-jupyter.html 
I'm using localtileserver v.0.6.1
Displaying the same image locally works perfectly. Also, checked that displaying the same image with matplotlib for example worked as well - e.g. source file is readable and path is correct.
Also, I've encountered a 404 Client Error, when not specifying default_projection for RemoteTileClient (my data is in EPSG:3031), while for TileClient it was not necessary

**Comment by banesullivan** [comment]
> As far as I understand, instead of TileClient function I need to use RemoteTileClient.
I've tried already:

Actually no! `RemoteTileClient` is meant for using a remotely hosted tile server with remotely hosted images... I may need to clarify that in the documentation.

You'll still want to use `TileClient` instead and should be able to pass the host and port easily to it:

https://localtileserver.banesullivan.com/api/index.html#localtileserver.TileClient

**Comment by banesullivan** [comment]
You will likely need to use `jupyter-server-proxy` to access the port the tiles are being served from. Check out https://localtileserver.banesullivan.com/installation/remote-jupyter.html for tips

**Comment by Dodekaphonia** [comment]
Thank you for the answer. As I still haven't succeed in showing image on map, I have to ask more questions.
I'm working on remote server with JupyterHub running. I'm connecting to it through, for example, mysite.com:8000/user/username/lab?
I've followed this instruction https://localtileserver.banesullivan.com/installation/remote-jupyter.html, installed` jupyter-server-proxy`, exported variable, and then set host forwarding.
In case of using `TileClient`:
- Do I need to specify `port`? It could be a random number?
- What is the right way to specify `client_host`?`127.0.0.1`, `mysite.com`, `user/username/`?
- What `client_port`  should I pass? 8000, random, or one received with `list(notebookapp.list_running_servers())`?
- On the step of exporting variable, do I need to write exactly 'proxy/{port}', and not to write 'proxy/8000', e.g. print specific port?

**Comment by banesullivan** [comment]
You should follow similar instructions on how to set up for MyBinder (as it is a JupyterHub). For the MyBinder here: https://mybinder.org/v2/gh/banesullivan/localtileserver-demo/HEAD

I set it up by:

1. Installing `jupyter-server-proxy` which you've done,
2. Figure out what the JupyterHub URL prefix is. On MyBinder, this is set as `JUPYTERHUB_SERVICE_PREFIX`, but if this is a custom server, it's probably just `user/<username>/` (on MyBinder, it's `/user/banesullivan-lo-tileserver-demo-zk38psb0/` for me right now)
3. Set up the `LOCALTILESERVER_CLIENT_PREFIX` environment variable as a template for the URL with that prefix such that it is a relative URL (essentially ignoring the host)

```py
import os
service_prefix = ''
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = f"{service_prefix}/proxy/{{port}}"
```

Where in this example, `LOCALTILESERVER_CLIENT_PREFIX` would be `'/user/<username>/proxy/{port}'` and that should be all you need for JupyterHub.

-----

Now to directly address your questions:

> Do I need to specify port? It could be a random number?

Nope! This is handled in the URL template built above and the `TileClient` will automatically put the right port in the `{{port}}` spot

> What is the right way to specify client_host?127.0.0.1, mysite.com, user/username/?

You should leave this alone and use a relative URL. The web browser will make the request from the base host, whatever it is.

> What client_port should I pass? 8000, random, or one received with list(notebookapp.list_running_servers())?

If setting `LOCALTILESERVER_CLIENT_PREFIX`, you should leave this alone as it's handled in th`{port}` field of the template.


> On the step of exporting variable, do I need to write exactly 'proxy/{port}', and not to write 'proxy/8000', e.g. print specific port?

Yes! There needs to be `{port}` field in the template.

**Comment by banesullivan** [comment]
@Dodekaphonia, feel free to poke around in that MyBinder for insight: https://mybinder.org/v2/gh/banesullivan/localtileserver-demo/HEAD

The GitHub repo where it's all configured is here: https://github.com/banesullivan/localtileserver-demo

And on start, you can see `LOCALTILESERVER_CLIENT_PREFIX ` getting set here: https://github.com/banesullivan/localtileserver-demo/blob/main/start

**Comment by banesullivan** [comment]
I find it helpful to play arround with the network tab in the chrome dev resources to see the URL that's working:

<img width="1649" alt="Screen Shot 2023-01-29 at 9 53 36 AM" src="https://user-images.githubusercontent.com/22067021/215342072-65083162-7a3f-4ff6-a0af-29c4f00f873c.png">


On that MyBinder instance, tiles are coming from:

```
https://hub.ovh2.mybinder.org/user/banesullivan-lo-tileserver-demo-zk38psb0/proxy/35385/api/tiles/9/144/220.png?&filename=/home/jovyan/bahamas_rgb.tif&n_colors=255&projection=EPSG:3857
```

Which matches the template of 

```
/user/banesullivan-lo-tileserver-demo-zk38psb0/proxy/{port}
```

The host of `https://hub.ovh2.mybinder.org/` doesn't matter because the request is made as a relative URL

**Comment by banesullivan** [comment]
@Dodekaphonia, if you get this working and would like to help clarify the documentation for this, I'd greatly appreciate some contributions to the docs here

**Comment by banesullivan** [comment]
Things are often a little different for every JupyterHub deployment, so take a look at this comment where another user had similar issues: https://github.com/banesullivan/localtileserver/issues/95#issuecomment-1193360130

**Comment by banesullivan** [comment]
there are also some useful tip's in `jupyter-server-proxy`'s docs: https://jupyter-server-proxy.readthedocs.io/en/latest/arbitrary-ports-hosts.html#with-jupyterhub

**Comment by Dodekaphonia** [comment]
@banesullivan, thank you so much for answering my questions in such detail. I will let you know what the result was.

**Comment by JosephKuchar** [comment]
Hi, I'm having the same issue, but within jupyterlab. I've installed jupyter-server-proxy, and exported the environment variable `export LOCALTILESERVER_CLIENT_PREFIX='proxy/{port}'`, but I'm still not seeing anything appear on the basemap. I'm trying one of the examples from the documentation, and it works up to the point of showing the basemap and has no errors, but does not show the tiles on top (but clearly is reading them because it is centering the map on the correct place). I'd appreciate any help!

```
-------------------------------------------------------------------------------
  Date: Fri Apr 21 10:00:35 2023 EDT

                     OS : Linux
                 CPU(s) : 52
                Machine : x86_64
           Architecture : 64bit
                    RAM : 251.4 GiB
            Environment : Jupyter
            File system : ext4

  Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03)
  [GCC 11.3.0]

        localtileserver : 0.6.4
                  flask : 2.1.3
          flask_caching : 1.10.1
             flask_cors : 3.0.10
            flask_restx : 1.0.6
               requests : 2.28.2
               werkzeug : 2.1.2
                  click : 8.1.3
          server_thread : 0.2.0
                 scooby : 0.7.1
            large_image : 1.20.4
large_image_source_gdal : 1.20.4
             cachetools : 5.3.0
                    PIL : 9.5.0
                 psutil : 5.9.0
                  numpy : 1.24.2
             palettable : 3.3.3
                 pyproj : 3.5.0
             osgeo.gdal : 3.6.3
              traitlets : 5.7.1
                 folium : 0.14.0
```

**Comment by banesullivan** [comment]
@JosephKuchar, the 251.4 GiB of available ram makes me think you're in a managed Jupyter*Hub* environment, is that right? If so, the URL path prefix will need to be more that just `'proxy/{port}`'. If you look at the URL of the notebook, you probably see your username in there -- you'll need that prefix in the there as well. 

This is vaguely referenced on https://localtileserver.banesullivan.com/installation/remote-jupyter.html and there might be better instructions in the comment above: https://github.com/banesullivan/localtileserver/issues/134#issuecomment-1407713896

See if `JUPYTERHUB_SERVICE_PREFIX` is in your environment. If so, combine them:

```py
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = f"{os.environ['JUPYTERHUB_SERVICE_PREFIX']}/proxy/{{port}}"
```

Hope this helps

---

> it works up to the point of showing the basemap and has no errors, but does not show the tiles on top (but clearly is reading them because it is centering the map on the correct place).

FYI, the tile URL is likely 404'ing -- which for mapping libraries means there are no tiles available and they gracefully ignore these errors. This is why ipyleaflet (or folium) do not show an error when the URL is misconfigured. All of this indeed makes debugging the URL tough. I find it helps to check the network tab of the chrome dev tools to find the tile URL requests and see what's happening

**Comment by JosephKuchar** [comment]
Thanks for the quick response! You're right, it turns out it is Jupyter Hub. However, there is no JUPYTERHUB_SERVICE_PREFIX environment variable set. 

If I look at the network tab, every status is 200, which I think means everything is being received?

I've added `os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'user/USER_NAME/proxy/{{port}}'` to the top of the script, no dice so far. Is there a command to identify that the prefix should be?

**Comment by banesullivan** [comment]
You probably need a `/` before `user/...`

**Comment by JosephKuchar** [comment]
I'm afraid that didn't do it! Any chance it can be gleaned from the url of the notebook? `http://localhost:8000/user/USERNAME/lab/tree/Mapping_Testing/folium_testing.py`

**Comment by banesullivan** [comment]
> http://localhost:8000

Wait. You're running locally? I thought this was a remote JupyterHub instance? You must be proxying the port through your system?

This sounds familiar to https://github.com/pyvista/pyvista/issues/3979#issuecomment-1431516908

**Comment by JosephKuchar** [comment]
Yes, sorry - We have a remote machine we ssh on to and that we set up our conda environments on, and proxy the port locally! I didn't realise this was not the usual thing, sorry.

**Comment by banesullivan** [comment]
> and proxy the port locally!

You'll just need to proxy the localtileserver ports too. In the PyVista issue I linked above, the user there did a great job of outlining what is necessary. 

Unfortunately, I set up the PyVista and localtileserver quite differently. PyVista's server runs on a single port so it can be easily set. Localtileserver can sometimes run on many different ports per file source.

When opening an image with `localtileserver`, just set the port to something known like `8999` in the port argument of whatever code your running. Then forward that port as well and ignore any of the jupyter-server-proxy configuration as your host machine will then be handling all of the port proxying

**Comment by JosephKuchar** [comment]
Thank you, that's solved it! I set an arbitrary port and forwarded that to my local machine:
`LocalForward 5124 localhost:5124`

Then just added port=5124 in the localtileserver arguments,

```
client = TileClient(input_file, port=5124)
# Create folium tile layer from that server
t = get_folium_tile_layer(client,port=5124)

m = Map(location=client.center(), zoom_start=16)
m.add_child(t)
```
And it is now working as expected. Thanks so much for your help!

**Comment by banesullivan** [comment]
Fantastic! Glad you got it working! 

I'm going to close this issue now as I think both folks here managed to get it working

**Comment by giswqs** [comment]
This is a very helpful discussion. I will need to revisit this later on for accessing localtileserver on Amazon SageMaker. Thank you.
