### ISSUE TITLE
Cannot display raster in Google Colab

### ISSUE THREAD

**Issue by Flawks** [banesullivan/localtileserver#165]
I'm trying to display the GeoTIFF image in Google Colab using the example code from the readme. The map zooms itself to the correct coordinates, but the raster is not visible. 

Here is the code I'm using:
```
!pip install localtileserver
!pip install ipyleaflet

from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

client = TileClient('image.tif')
t = get_leaflet_tile_layer(client)

m = Map(center=client.center(), zoom=client.default_zoom)
m.add_layer(t)
m
```

Here is the output:
![Screenshot1](https://github.com/banesullivan/localtileserver/assets/45131492/d2527b5d-50ec-475c-95f8-24a9d3128709)

This is the output of `print(localtileserver.Report())` :

`--------------------------------------------------------------------------------
  Date: Thu Jul 20 09:53:09 2023 UTC

                         OS : Linux
                     CPU(s) : 2
                    Machine : x86_64
               Architecture : 64bit
                        RAM : 12.7 GiB
                Environment : IPython

  Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]

            localtileserver : 0.7.1
                      flask : 2.2.5
              flask_caching : 2.0.2
                 flask_cors : 4.0.0
                flask_restx : 1.1.0
                   requests : 2.27.1
                   werkzeug : 2.3.6
                      click : 8.1.4
              server_thread : 0.2.0
                     scooby : 0.7.2
                large_image : 1.23.1
large_image_source_rasterio : 1.23.1
                 cachetools : 5.3.1
                        PIL : 8.4.0
                     psutil : 5.9.5
                      numpy : 1.22.4
                 palettable : 3.3.3
                 ipyleaflet : 0.17.3
                  traitlets : 5.7.1
                    shapely : 2.0.1
                     folium : 0.14.0
                 matplotlib : 3.7.1
                   colorcet : 3.0.1
                 osgeo.gdal : 3.4.3
                     pyproj : 3.6.0
--------------------------------------------------------------------------------`

**Comment by giswqs** [comment]
It used to work with Colab before. Some recent updates might have caused this.

**Comment by banesullivan** [comment]
Hm. No sure what is going wrong here but I am able to get localtileserver working out of the box in Colab here: https://colab.research.google.com/drive/1h1iTDl4KqbXxKiyox9eM211vAg6_ONKT?usp=sharing

**Comment by banesullivan** [comment]
Can you view other rasters like the example datasets? Is it possible that this dataset might not be displayed correctly? Could you share the data file?

**Comment by banesullivan** [comment]
That linked example is currently working when I try it in a few different browsers. I suspect something is going awry with your Colab environment and it's forwarding of the necessary ports
