### ISSUE TITLE
send_file() got an unexpected keyword argument 'download_name'

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#17]
I am testing it with a local GeoTIFF (download [here](https://drive.google.com/file/d/1EV38RjNxdwEozjc9m0FcO3LFgAoAX1Uw/view?usp=sharing)) and got the following error. The tile does not show up on the map. 

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

url = "/home/qiusheng/Downloads/landsat.tif"
# First, create a tile server from local raster file
tile_client = TileClient(url)

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m

```
![image](https://user-images.githubusercontent.com/5016453/143664410-b7fcf623-a946-45e1-91f9-d933e00cfaa4.png)

**Comment by banesullivan** [comment]
Please make sure your version of `Flask` is up to date. I recently saw deperecation warnings from flask in favor of the new `download_name` so be sure to update. To resolve this, I will set a minimum version of flask

See #19

**Comment by giswqs** [comment]
Updating flask solves the issue. BTW, is it possible to hide the warning `Created LRU Cache for 'tilesource' with 39 maximum size`?  Is it originated from the `large-image` package? Using the following two lines still shows that warning message.

```python
import warnings
warnings.filterwarnings("ignore")
```


![image](https://user-images.githubusercontent.com/5016453/143664819-36af143b-bc55-4b04-814f-839531fd80f5.png)

**Comment by banesullivan** [comment]
I'm working on that. It is an upstream issue with large image. See https://github.com/girder/large_image/pull/689

**Comment by aryans14** [comment]
Further error details from command prompt:

127.0.0.1 - - [2022-06-20 15:09:27] "GET / HTTP/1.1" 200 794 0.012084
127.0.0.1 - - [2022-06-20 15:09:28] "GET /boot HTTP/1.1" 200 178 0.000000
127.0.0.1 - - [2022-06-20 15:09:28] "GET /logo192.png HTTP/1.1" 404 156 0.000000
127.0.0.1 - - [2022-06-20 15:09:28] "GET /favicon.ico HTTP/1.1" 200 318 0.000000
127.0.0.1 - - [2022-06-20 15:09:32] "GET /api/projects/stats HTTP/1.1" 200 196 0.000000
127.0.0.1 - - [2022-06-20 15:09:32] "GET /api/projects HTTP/1.1" 200 609 0.000000
127.0.0.1 - - [2022-06-20 15:09:39] "GET /api/projects/new-paper-filterations/info HTTP/1.1" 200 596 0.000000
127.0.0.1 - - [2022-06-20 15:09:39] "GET /api/projects/new-paper-filterations/dataset_writer HTTP/1.1" 200 475 0.069026
127.0.0.1 - - [2022-06-20 15:09:39] "GET /static/media/ElasHoldingSIGNS_Finished.417f4491e95fc76527da3e41f6b8186f.svg HTTP/1.1" 200 323 0.000000
ERROR:asreview.webapp.start_flask:Exception on /api/projects/new-paper-filterations/export_dataset [GET]
Traceback (most recent call last):
  File "c:\users\avcd\anaconda3\lib\site-packages\asreview\webapp\api.py", line 1156, in api_export_dataset
    return send_file(
TypeError: send_file() got an unexpected keyword argument 'download_name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\avcd\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\avcd\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\avcd\anaconda3\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\avcd\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\avcd\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\avcd\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\avcd\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\avcd\anaconda3\lib\site-packages\asreview\project.py", line 84, in decorated_function
    return f(project, *args, **kwargs)
  File "c:\users\avcd\anaconda3\lib\site-packages\asreview\webapp\api.py", line 1163, in api_export_dataset
    raise Exception(f"Failed to export the {file_format} dataset. {err}")
Exception: Failed to export the csv dataset. send_file() got an unexpected keyword argument 'download_name'
ERROR:root:Failed to export the csv dataset. send_file() got an unexpected keyword argument 'download_name'
