### ISSUE TITLE
Generated PNG tiles are not transparent (have black background)

### ISSUE THREAD

**Issue by jovanovski** [banesullivan/localtileserver#171]
I am generating a tile server using the `leafmap` package, to add a raster TIFF file. The file renders correctly in QGIS for example, only showing data where data exists (see image 1). But when generating with this package, the resulting PNG tiles have a black background where there is supposed to be no data (see image 2) (there is a map tile layer underneath it).
<img width="336" alt="image" src="https://github.com/banesullivan/localtileserver/assets/5332928/e3cfb560-44d4-4861-b464-22bbcb781e57">

<img width="336" alt="image" src="https://github.com/banesullivan/localtileserver/assets/5332928/2ebd5c70-c1a7-49a7-8d6e-c8bb4a684f6a">

How can I generate images with a transparent background where there is no data?

**Comment by giswqs** [comment]
Set nodata=None?

**Comment by jovanovski** [comment]
> Set nodata=None?

I did explicitly, even though it defaults to `None` anyway. Tried `0` as well.
