### ISSUE TITLE
Remote COG no longer works

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#172]
It seems the remote COG example is broken. The tiles do not show up. 
https://localtileserver.banesullivan.com/user-guide/remote-cog.html

**Comment by giswqs** [comment]
The error in the console
![image](https://github.com/banesullivan/localtileserver/assets/5016453/9bc79545-2399-435b-b217-4e18acc6e45f)

**Comment by banesullivan** [comment]
Those console logs are unrelated to this issue.

Something odd is happening here as it is indeed broken for the dataset in the linked example and a couple others I tried (but it is not broken for all remote files). I'm not sure where this is going awry at this time and have limited bandwidth to look into this...

**Comment by banesullivan** [comment]
Confirmed that this is a bug with large-image's `RasterioFileTileSource`. I'm working to switch to use rio-tiler here so this may have to wait until I finish that (substantial work)

**Comment by banesullivan** [comment]
This will be fixed in the next release (0.10.0) during the switch to using rio-tiler which better handles this
