### ISSUE TITLE
Tiff file saving to HTML using folium

### ISSUE THREAD

**Issue by Sudhip007** [banesullivan/localtileserver#174]
Hi Team,

I have run the raster image with localtileserver and at the end I saved the map into html format. It displayed my raster image, but after closing jupyter notebook and I opened my saved html file then it not displaying my raster image. Please, help me out in this issue.

I used folium for this.

Thanks..

**Comment by banesullivan** [comment]
This requires a live server/kernel so you cannot save as a standalone html file.
