### ISSUE TITLE
Tileclient does not show when run dash app python on docker

### ISSUE THREAD

**Issue by trantunhi99** [banesullivan/localtileserver#175]
Hi,
i used your package as part of my dash app to display some image. I created an image on docker, everything is good except  Tileclient image does not show up. Im kinda brand new to this so im really sorry if i ask something stupid

**Comment by banesullivan** [comment]
Would you share some code to help me reproduce what you are experiencing?

**Comment by trantunhi99** [comment]
hi, sorry for the really late response, right now our code is too long to give you a small example. have you ever try using your package on a dash app before and running on a remote server?

**Comment by banesullivan** [comment]
> running on a remote server

I suspect the browser simply cannot access the port on which the tiles are being served. The port will need to be proxied
