### ISSUE TITLE
localtileserver not working with Leafmap on Docker

### ISSUE THREAD

**Issue by EmanuelCastanho** [banesullivan/localtileserver#179]
I am using the following Docker image:
`docker run -it -p 8888:8888 -v "${PWD}"/Desktop/test:/home/jovyan/test jupyter/base-notebook:python-3.10`

When I open the notebook I install the following packages:
```
!pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL==3.8.0 --quiet
print("GDAL checked!")
!pip install localtileserver==0.7.2 --quiet
print("localtileserver checked!")
!pip install geopandas==0.14.0 --quiet
print("geopandas checked!")
!pip install leafmap==0.27.0 --quiet
print("leafmap checked!")
!pip install scikit-learn==1.1.1 --quiet # To load the model you need the same version
print("scikit-learn checked!")
!pip install pyarrow==13.0.0 --quiet
print("pyarrow checked!")
```

After that I import all the necessary packages without a problem and start my coding:
```
m = leafmap.Map(location=[31.4710, -29.6108], zoom_start=5)
m.add_raster(stack_fullpath, band=[4, 3, 2], vmin=0, vmax=0.15, layer_name="RGB")
m
```

On my computer the map shows with the RGB layer, but on Docker it does not show. Only shows an empty map.

Can someone replicate this?

**Comment by banesullivan** [comment]
Make sure you install and use `jupyer_server_proxy` to forward the port through the Jupyter web connection

**Comment by banesullivan** [comment]
A handful of issues have been opened regarding this, so if in doubt try searching around the issues here. #66 might help

**Comment by banesullivan** [comment]
You can also experiment with my Docker set up here: https://github.com/banesullivan/localtileserver/blob/main/Dockerfile

Which if I recall correctly, just installing `jupyter_server_proxy` should handle everything

**Comment by EmanuelCastanho** [comment]
Thank you for the quick support!
I changed your Docker set up to work with Python 3.9 (because of scikit 1.1.1) and it is working now:

```
FROM jupyter/base-notebook:python-3.9

USER jovyan

RUN python -m pip install --upgrade pip

RUN pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL==3.8.0
RUN pip install localtileserver==0.7.2
RUN pip install geopandas==0.14.0
RUN pip install leafmap==0.27.0
RUN pip install scikit-learn==1.1.1
RUN pip install pyarrow==13.0.0
RUN pip install jupyter-server-proxy==4.1.0

ENV JUPYTER_ENABLE_LAB=yes

ARG LOCALTILESERVER_CLIENT_PREFIX='proxy/{port}'
ENV LOCALTILESERVER_CLIENT_PREFIX=$LOCALTILESERVER_CLIENT_PREFIX
```
