### ISSUE TITLE
localtileserver client cannot work after setting the http proxy

### ISSUE THREAD

**Issue by Simplify-2023** [banesullivan/localtileserver#180]
**Code**
`from localtileserver import TileClient, get_leaflet_tile_layer, examples`
`from ipyleaflet import Map`
`import localtileserver`
`import os`

`os.environ["HTTP_PROXY"] = "http://127.0.0.1:7890"`
`os.environ["HTTPS_PROXY"] = "http://127.0.0.1:7890"`
`client = examples.get_san_francisco()`
`client`

**Error Message**
> ---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File D:\Anaconda\envs\gee\lib\site-packages\IPython\core\formatters.py:922, in IPythonDisplayFormatter.__call__(self, obj)
    920 method = get_real_method(obj, self.print_method)
    921 if method is not None:
--> 922     method()
    923     return True

File D:\Anaconda\envs\gee\lib\site-packages\localtileserver\client.py:440, in BaseTileClientInterface._ipython_display_(self)
    436 from ipyleaflet import Map, WKTLayer, projections
    438 from localtileserver.widgets import get_leaflet_tile_layer
--> 440 t = get_leaflet_tile_layer(self)
    441 if self.default_projection is None:
    442     m = Map(
    443         basemap=t,
    444         min_zoom=0,
   (...)
    447         crs=projections.Simple,
    448     )

File D:\Anaconda\envs\gee\lib\site-packages\localtileserver\widgets.py:108, in get_leaflet_tile_layer(source, port, debug, projection, band, palette, vmin, vmax, nodata, scheme, n_colors, attribution, style, cmap, default_projection, **kwargs)
    103 class BoundTileLayer(TileLayer, LocalTileServerLayerMixin):
    104     # https://github.com/jupyter-widgets/ipyleaflet/issues/888
    105     # https://github.com/ipython/traitlets/issues/626#issuecomment-699957829
    106     bounds = Union((Tuple(),), default_value=None, allow_none=True).tag(sync=True, o=True)
--> 108 source, created = get_or_create_tile_client(
    109     source, port=port, debug=debug, default_projection=default_projection
    110 )
    111 url = source.get_tile_url(
    112     projection=projection,
    113     band=kwargs.get("bands", band),
   (...)
    122     client=True,
    123 )
    124 if attribution is None:

File D:\Anaconda\envs\gee\lib\site-packages\localtileserver\client.py:1011, in get_or_create_tile_client(source, port, debug, default_projection)
   1009         source.shutdown()
   1010         del source
-> 1011     raise e
   1012 return source, _internally_created

File D:\Anaconda\envs\gee\lib\site-packages\localtileserver\client.py:1005, in get_or_create_tile_client(source, port, debug, default_projection)
   1003 try:
   1004     r = requests.get(source.create_url("api/metadata"))
-> 1005     r.raise_for_status()
   1006 except requests.HTTPError as e:
   1007     # Make sure to destroy the server and its thread if internally created.
   1008     if _internally_created:

File D:\Anaconda\envs\gee\lib\site-packages\requests\models.py:1021, in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 502 Server Error: Bad Gateway for url: http://localhost:58836/api/metadata?&filename=%2Fvsicurl%3Furl%3Dhttps%253A%252F%252Fdata.kitware.com%252Fapi%252Fv1%252Ffile%252F626854a14acac99f42126a74%252Fdownload%26use_head%3Dno%26list_dir%3Dno
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
File D:\Anaconda\envs\gee\lib\site-packages\IPython\core\formatters.py:344, in BaseFormatter.__call__(self, obj)
    342     method = get_real_method(obj, self.print_method)
    343     if method is not None:
--> 344         return method()
    345     return None
    346 else:

File D:\Anaconda\envs\gee\lib\site-packages\localtileserver\client.py:461, in BaseTileClientInterface._repr_png_(self)
    460 def _repr_png_(self):
--> 461     with open(self.thumbnail(encoding="PNG"), "rb") as f:
    462         return f.read()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

**Comment by banesullivan** [comment]
Not sure what instructions you are following to set `HTTP_PROXY` but this is not a part of `localtileserver`. Please read the documentation for remote environments: https://localtileserver.banesullivan.com/installation/remote-jupyter.html

**Comment by Simplify-2023** [comment]
> Not sure what instructions you are following to set `HTTP_PROXY` but this is not a part of `localtileserver`. Please read the documentation for remote environments: https://localtileserver.banesullivan.com/installation/remote-jupyter.html

I am running geemap in China using vpn, thus I need to set the http proxy to 7890 to enable geemap works. 
To follow your instruction, I just installed jupyter-server-proxy, but when I moved to the next step `export LOCALTILESERVER_CLIENT_PREFIX='proxy/{port}'`, the consoles occured an error said 'SyntaxError: invalid syntax'.

**Comment by banesullivan** [comment]
That code snippet was `bash`. The Python equivalent would be:

```py
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'
```

Make sure you set that before importing `localtileserver`

**Comment by Simplify-2023** [comment]
> That code snippet was `bash`. The Python equivalent would be:
> 
> ```python
> import os
> os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = 'proxy/{port}'
> ```
> 
> Make sure you set that before importing `localtileserver`

Unfortunately, same error occurs though I follow your instruction.
