### ISSUE TITLE
nodata causes padding

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#197]
When `nodata` is set to a certain value (e.g., -1), there are some big black empty tiles surrounding the image. 

```python
from localtileserver import TileClient, get_leaflet_tile_layer, examples
from ipyleaflet import Map

client = TileClient('https://github.com/giswqs/data/raw/main/raster/landsat7.tif')
t = get_leaflet_tile_layer(client, nodata=-1)
m = Map(center=client.center(), zoom=client.default_zoom)
m.add(t)
m
```

`nodata = -1`
![Peek 2024-02-07 21-51](https://github.com/banesullivan/localtileserver/assets/5016453/0f5a169c-ec75-45d7-abf9-645a7defdaba)

`nodata=None`
![image](https://github.com/banesullivan/localtileserver/assets/5016453/d9e6c376-4ac7-4d15-b0ae-71605eacc0d8)

I noticed the example on the documentation page has a similar issue (a white background). However, it displays correctly when used locally. 
https://localtileserver.banesullivan.com/
![image](https://github.com/banesullivan/localtileserver/assets/5016453/690df60a-2672-437c-8d39-931dabb120f8)

Local jupyter
![image](https://github.com/banesullivan/localtileserver/assets/5016453/0116ae13-32d4-4118-a558-46778b1b3456)

**Comment by banesullivan** [comment]
I've also noticed this occasionally and I think it has to do with whether your browser is in light mode or dark mode. 

I reported a similar (perhaps?) issue upstream at one point but haven't made time to dive into it: https://github.com/jupyter-widgets/ipyleaflet/issues/1059

To things to test:

1. Does changing to "light mode" fix it?
2. Does using `folium` instead of `ipyleaflet` fix this?

**Comment by banesullivan** [comment]
I'm unable to reproduce locally at the moment... and have a strong hunch that this is a browser CSS/styling issue

**Comment by giswqs** [comment]
I tried light mode on my local Jupyter and Google Colab. This issue persists. Same thing for folium. 

![image](https://github.com/banesullivan/localtileserver/assets/5016453/96222c8d-10a7-4928-8094-75b6a085ca09)

**Comment by banesullivan** [comment]
Okay thanks for trying these. I'll work to reproduce this reliably and see what I can do

**Comment by banesullivan** [comment]
Would you please share a Report? localtileserver.Report()

**Comment by giswqs** [comment]
![image](https://github.com/banesullivan/localtileserver/assets/5016453/ce83ab9a-b970-4997-92be-bbdbd8f6a60d)

**Comment by banesullivan** [comment]
The issue on the docs page is something else related to styling.

The issue you are reporting here might be upstream in rio-tiler:

```py
from rio_tiler.io import Reader

class PNG(bytes):
    def _repr_png_(self):
        return self

reader = Reader('https://github.com/giswqs/data/raw/main/raster/landsat7.tif')
img = reader.tile(82, 198, 9, nodata=0)
PNG(img.render(img_format="png"))
```
![download](https://github.com/banesullivan/localtileserver/assets/22067021/8cef848e-0636-40fe-9379-5d5649a98531)

```py
img = reader.tile(82, 198, 9, nodata=-1)
PNG(img.render(img_format="png"))
```
![download](https://github.com/banesullivan/localtileserver/assets/22067021/c0f1fb82-cd6e-4614-8687-054ac1b1d095)

**Comment by vincentsarago** [comment]
👋 after some time looking at the issue I've realized the problems are:

- you're trying to use `-1` nodata value on a `uint16` dataset, to GDAL will ignore it
- your data is a RGB with a bad nodata value (**0**) but this `0` value is proper data 

```
gdalinfo https://github.com/giswqs/data/raw/main/raster/landsat7.tif
Driver: GTiff/GeoTIFF
Files: none associated
Size is 2181, 1917
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Popular Visualisation Pseudo-Mercator",
        METHOD["Popular Visualisation Pseudo Mercator",
            ID["EPSG",1024]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Web mapping and visualisation."],
        AREA["World between 85.06°S and 85.06°N."],
        BBOX[-85.06,-180,85.06,180]],
    ID["EPSG",3857]]
Data axis to CRS axis mapping: 1,2
Origin = (-13651650.000000000000000,4576290.000000000000000)
Pixel Size = (30.000000000000000,-30.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  OVR_RESAMPLING_ALG=NEAREST
  TIFFTAG_RESOLUTIONUNIT=1 (unitless)
  TIFFTAG_XRESOLUTION=1
  TIFFTAG_YRESOLUTION=1
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=PIXEL
  LAYOUT=COG
Corner Coordinates:
Upper Left  (-13651650.000, 4576290.000) (122d38' 5.49"W, 37d58'40.08"N)
Lower Left  (-13651650.000, 4518780.000) (122d38' 5.49"W, 37d34'10.00"N)
Upper Right (-13586220.000, 4576290.000) (122d 2'49.53"W, 37d58'40.08"N)
Lower Right (-13586220.000, 4518780.000) (122d 2'49.53"W, 37d34'10.00"N)
Center      (-13618935.000, 4547535.000) (122d20'27.51"W, 37d46'26.05"N)
Band 1 Block=512x512 Type=Byte, ColorInterp=Red
  NoData Value=0
  Overviews: 1091x959, 546x480
Band 2 Block=512x512 Type=Byte, ColorInterp=Green
  NoData Value=0
  Overviews: 1091x959, 546x480
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
  NoData Value=0
  Overviews: 1091x959, 546x480
```


<img width="684" alt="Screenshot 2024-02-13 at 5 46 23 PM" src="https://github.com/banesullivan/localtileserver/assets/10407788/e7645251-a380-40e7-ad76-70c0f4c11bc2">

Sadly there is no option in rio-tiler to `ignore` nodata value (just to overwrite) 😓 

The easiest way to fix this is to edit the file and to remove the `nodata` value

**Comment by giswqs** [comment]
@vincentsarago Thank you for looking into it. QGIS has an option for ignoring the nodata value. Localtileserver used to be able to ignore the nodata value as well. It would be great if rio-tiler can support this as well. The zero value is very common in remote sensing imagery. 

![image](https://github.com/banesullivan/localtileserver/assets/5016453/355721b8-c59a-4445-a124-6391b5506fb5)

![image](https://github.com/banesullivan/localtileserver/assets/5016453/fa01648d-3f26-4f23-b90f-62257f6cff40)

**Comment by giswqs** [comment]
Here is the PR that fixed the nodata issue two years ago. https://github.com/banesullivan/localtileserver/pull/60
I wondered if something similar can be done with rio-tiler.

**Comment by giswqs** [comment]
Some werid behavior. Increasing the nodata value will result in a colorful background, which is unexpected.  

```python
from localtileserver import TileClient, get_leaflet_tile_layer, examples
from ipyleaflet import Map

client = TileClient('https://github.com/giswqs/data/raw/main/raster/landsat7.tif')
t = get_leaflet_tile_layer(client, nodata=254)
m = Map(center=client.center(), zoom=client.default_zoom)
m.add(t)
m
```

`nodata=0`
![image](https://github.com/banesullivan/localtileserver/assets/5016453/671998e5-b4c5-409f-b561-dc26ac1a30f1)

`nodata=100`
![image](https://github.com/banesullivan/localtileserver/assets/5016453/f221ee86-3dc8-4ebf-ad55-c6f870111754)

`nodata=254`
![image](https://github.com/banesullivan/localtileserver/assets/5016453/0f0aaaa6-3528-4ff5-ae54-83ae04929030)

**Comment by vincentsarago** [comment]
the data outside the raster is set to 0 instead of -1 (because of the datatype issue) so then when we are building the mask we don't find the `-1` value

**Comment by banesullivan** [comment]
Ah okay. Thanks for looking so deeply into this @vincentsarago! I'm going to mark this issue as closed since it is really a data-specific issue
