### ISSUE TITLE
The vmin and vmax parameters have no effect

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#198]
It seems the `vmin` and `vmax` parameters have no effect. The rendered image look the same no matter what `vmin` and `vmax` values. 

```python
from localtileserver import get_leaflet_tile_layer, examples
from ipyleaflet import Map

client = examples.get_san_francisco()
t = get_leaflet_tile_layer(client, vmin=50,vmax=100)
m = Map(center=client.center(), zoom=client.default_zoom)
m.add(t)
m
```
![image](https://github.com/banesullivan/localtileserver/assets/5016453/ce307aec-37ba-484c-ad56-0003d992ed7b)

**Comment by banesullivan** [comment]
@giswqs, I'm going to implement some image regression testing to validate all of these things truly work, then I'll issue a patch release

**Comment by giswqs** [comment]
Thank you for fixing it so quickly 👍
