### ISSUE TITLE
Support band selection for multi-spectral imagery

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#22]
The `band` parameter of `get_leaflet_tile_layer()` is an integer type. I would suggest adding support for band selection when there are more than 3 bands, e.g., `band=[4, 3, 2]` 

Sample dataset: [landsat.tif](https://drive.google.com/file/d/1EV38RjNxdwEozjc9m0FcO3LFgAoAX1Uw/view?usp=sharing) (7 bands)

```python
from localtileserver import get_leaflet_tile_layer, TileClient
from ipyleaflet import Map

url = "/home/qiusheng/Downloads/landsat.tif"
# First, create a tile server from local raster file
tile_client = TileClient(url)

# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)

# Create ipyleaflet map, add tile layer, and display
m = Map(center=tile_client.center())
m.add_layer(t)
m
```
![image](https://user-images.githubusercontent.com/5016453/143665956-f116fee7-fad8-4cf6-b946-7737642c9e1e.png)

In QGIS
![image](https://user-images.githubusercontent.com/5016453/143665970-facdb1dc-4b6b-419e-9efa-849fa12808e8.png)

**Comment by banesullivan** [comment]
This is absolutely doable but will require a bit of work. I don't have a timeline for this but I absolutely will implement this
