### ISSUE TITLE
AttributeError: 'Info' object has no attribute 'minzoom'

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#225]
Localtileserver stopped working on Colab. Not sure if this a pydantic or localtileserver issue. 

```python
from localtileserver import TileClient, get_leaflet_tile_layer, examples
from ipyleaflet import Map

client = examples.get_san_francisco()  # use example data

t = get_leaflet_tile_layer(client)
m = Map(center=client.center(), zoom=client.default_zoom)
m.add(t)
m
```
![image](https://github.com/user-attachments/assets/296ecf9f-2185-4793-9f61-5d89629ab4e0)

Relevant issue: https://github.com/opengeos/segment-geospatial/issues/351

**Comment by dfguerrerom** [comment]
the root of the error is in https://github.com/cogeotiff/rio-tiler/issues/757

**Comment by dfguerrerom** [comment]
I think it can be fixed if `rio-tiler<7` is set as requirement

**Comment by giswqs** [comment]
@dfguerrerom Thank you for looking into it. I hope it can be fixed in rio-tiler. Setting `rio-tiler<7` is not a permanent solution.

**Comment by dfguerrerom** [comment]
yes, a temporary solution until it is fixed

**Comment by giswqs** [comment]
I made a temporary fix in leafmap. Hope rio-titler can fix it soon. 
https://github.com/opengeos/leafmap/pull/929/files

**Comment by vincentsarago** [comment]
It's not an issue with rio-tiler
We've remove the min/max zoom attribute in the Info response 
Please see the rio-tiler docs/changelog 
Also make sure to pin rio-tiler so you don't get those issue when we push breaking changes

**Comment by giswqs** [comment]
@vincentsarago Thank you for the information. Any alternative to get the `minzoom` from rio-tiler? 

I think we just need to update these Line 92 & 100 in localtileserver. 

https://github.com/banesullivan/localtileserver/blob/4ba30afc56a92e430c2588ccf44036d233fc9268/localtileserver/client.py#L90-L100

**Comment by giswqs** [comment]
I see. They are now the dataset properties. 

#### Properties

- **bounds**: dataset's bounds (in dataset crs)
- **crs**: dataset's crs
- **minzoom**: dataset's minzoom (in TMS)
- **maxzoom**: dataset's maxzoom (in TMS)
- **transform**: dataset's Affine transform
- **height**: dataset's height
- **width**: dataset's width

```python
from rio_tiler.io import Reader

with Reader("myfile.tif") as src:
    print(src.dataset)
    print(src.tms.identifier)
    print(src.minzoom)
    print(src.maxzoom)
    print(src.bounds)
    print(src.crs)
    print(src.colormap)
