### ISSUE TITLE
localtileserver with streamlit

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#26]
I created an interactive [streamlit](https://streamlit.io/) web app for visualizing local and remote COG based on localtileserver and leafmap. The web app works fine when running locally. However, when deployed to [Streamlit Cloud](https://streamlit.io/cloud), the tile layer won't show up. I turned on the debug mode and found that the app in streamlit cloud is missing `GET /tiles/`. See the screenshots and video demo below. Any advice? Thanks. 

Web App: https://share.streamlit.io/giswqs/streamlit-geospatial/app.py?page=Visualize+Raster+Data
Source code: https://github.com/giswqs/streamlit-geospatial/blob/master/apps/raster.py

The app running on Streamlit Cloud (missing `GET /tiles/` ) - layer not shown up
![image](https://user-images.githubusercontent.com/5016453/143720478-ce50c9ba-18db-4dac-aa05-67c45990f1f4.png)

The app running locally  (with `GET /tiles/` ) - layer shown up correctly
![image](https://user-images.githubusercontent.com/5016453/143720427-fef950ea-7aba-4dfe-b551-dac8342de156.png)

https://user-images.githubusercontent.com/5016453/143720329-fa20b1f8-3f1c-4cb0-9460-735d9d23da19.mp4

**Comment by banesullivan** [comment]
This is going to be pretty tough to track down with out further context/pointing to the code that useing `localtileser`... If GET /tiles isn't coming through, then that makes me think your web front-end isn't requesting tiles *or* your server can't handle the requested data file and its hung opening the file and the request isn't logged

**Comment by giswqs** [comment]
Closing this issue. A more general issue has been reported at https://github.com/banesullivan/localtileserver/issues/29

**Comment by banesullivan** [comment]
Ehh, I think this might actually be more general than dealing with Jupyter in #29.

Do you manage the webserver that is running this app? If so, you can specify the port for which localtileserver is running and make sure that is publically visible so that the web browser viewing the app has access to the tiles

**Comment by giswqs** [comment]
Yes, I am managing the free webserver provided by [Streamlit Could](https://streamlit.io/cloud). I am not sure if there is a way to specify the port and make it publicly visible. 

However, the app can also be deployed to other cloud providers, such as [Heroku](https://heroku.com/). Below is the code to start the server. 

https://github.com/giswqs/streamlit-geospatial/blob/master/setup.sh#L15
```
mkdir -p ~/.streamlit/
echo "\
[server]\n\
headless = true\n\
port = $PORT\n\
enableCORS = false\n\
\n\
" > ~/.streamlit/config.toml
```

**Comment by banesullivan** [comment]
I'm not familiar with streamlit cloud at all but AFAIK, with platforms like Heroku, you cannot make any port available, only 443 and 80 (for the homepage of your app). 

I suspect what you need to do is add new endpoints in your Streamlit app itself so it can be the tile server request manager (but I don't know anything about streamlit so perhaps the notion of adding new endpoints doesn't make sense)

.... This stuff just gets messy.... which is what I wanted to avoid by naming this ***local***tileserver 🤣

**Comment by giswqs** [comment]
Streamlit cloud behaves like Heroku. There is not much control you can do about the server. Let's stick with local stuff and forget about remote env. localtileserver does it really well in a local env.

**Comment by banesullivan** [comment]
FWIW, I may come back to this later and implement a more stable way to launch the backing Flask application on remote servers with a `RemoteTileClient` interface and changing the existing `TileClient` to `LocalTileClient`.

This would be quite easy if all of your files are hosted online either through https:// or s3://

But it'll require putting some thought into making sure the backing Flask application is actually production-ready. Further, I'm inclined to just point anyone hoping to do remote tile serving over to ResonantGeoData after pointing so much work into that platform. RGD isn't 100% ready for this use case, but if there is interest, I could make it ready

**Comment by banesullivan** [comment]
Well, deploying localtileserver on Heroku was an absolute breeze. I have a branch where I set this up in #30 

And here is a demo: http://127.0.0.1:5000/?filename=https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif

Simple pass any valid `https://` file (this might not work if the file URL has credentials or some sort of parameters in it)


I'll see if I can whip together a `RemoteTileClient` class to interface with this
