### ISSUE TITLE
add `api/` prefix to API URLs

### ISSUE THREAD

**Issue by banesullivan** [banesullivan/localtileserver#48]
The next minor version (v0.4.x) will rename many of the URLs for the API. e.g. `/tiles/{z}/{x}/{y}.png` -> `/api/tiles/{z}/{x}/{y}.png`

**Comment by banesullivan** [comment]
This should have a very minimal effect on downstream projects

**Comment by banesullivan** [comment]
@giswqs, if you're using RemoteTileClient, this may break during the release phase as I and you update everything

**Comment by banesullivan** [comment]
Since this is breaking, the next version will be `0.4.x`

**Comment by giswqs** [comment]
I don't use the API URL directly. As long as the `TileClient`  stays the same, I don't need to make any changes. 

https://github.com/giswqs/leafmap/blob/8bd65d9b42c0629d60b55f194d7e50ec04d9162a/leafmap/common.py#L3691
