### ISSUE TITLE
Support custom palettes for single band imagery

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#54]
Is it possible to support custom palettes (e.g., a list of hex color codes) when rendering a single band? 
For example: `["#006633", "#E5FFCC", "#662A00", "#D8D8D8", "#F5F5F5"]`

**Comment by banesullivan** [comment]
This is totally possible, and it's a regression that this is failing with `get_leaflet_tile_layer`. I will fix

**Comment by banesullivan** [comment]
FYI https://github.com/girder/large_image/issues/753
