### ISSUE TITLE
vmin and vmax

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#56]
How are `vmin` and `vmax` determined when plotting a single band with `vmin=None` and `vmax=None`? Are they derived from `TileClient.metadata()["bands"]` when users do not specify the values? 

From the documentation, it seems `vmin` and `vmax` only support single-band imagery. How about multi-band imagery? 

![image](https://user-images.githubusercontent.com/5016453/148655197-5a81df9c-c7e0-42a6-95cf-1202d715f789.png)

When plotting multi-band imagery using [titiler](https://github.com/developmentseed/titiler), I use the `percentile_2` and `percentile_98` as the default `vmin` and `vmax`.
https://github.com/giswqs/leafmap/blob/8bd65d9b42c0629d60b55f194d7e50ec04d9162a/leafmap/common.py#L979-L983

https://leafmap.org/notebooks/37_planetary_computer/
![image](https://user-images.githubusercontent.com/5016453/148655225-d67f1aa7-6d82-45e6-8a54-25fc2447db1d.png)

**Comment by banesullivan** [comment]
Most of this pertains to the upstream large_image package

> How are vmin and vmax determined when plotting a single band with vmin=None and vmax=None?

They are determined with GDAL's `GetStatistics()` method directly: https://github.com/girder/large_image/blob/1b537a1fef5326721f2c8048361aba3d9f702656/sources/gdal/large_image_source_gdal/__init__.py#L522-L525

Check out [`GetStatistics()`'s documentation](https://gdal.org/doxygen/classGDALRasterBand.html#a6aa58b6f0a0c17722b9bf763a96ff069) for some additional features it provides

> Are they derived from TileClient.metadata()["bands"] when users do not specify the values?

Exactly, yes


> From the documentation, it seems vmin and vmax only support single-band imagery. How about multi-band imagery?

Hm, the documentation is lacking here for sure. These are actually supported for multi-band imagery. Here is an example:

```py
from localtileserver import get_leaflet_tile_layer
from localtileserver import examples
from ipyleaflet import Map

tile_client = examples.get_san_francisco()

t = get_leaflet_tile_layer(tile_client, band=[1,2,3], palette=['r', 'g', 'b'], vmin=[0,0,0], vmax=[100,200,10])

m = Map(center=tile_client.center(), zoom=9)
m.add_layer(t)
m
```
<img width="1102" alt="Screen Shot 2022-01-08 at 11 41 58 AM" src="https://user-images.githubusercontent.com/22067021/148655858-b5c7b479-6982-41be-bbcf-42936fdaa8e1.png">


This scales each band in it's vmin/vmax range before mapping to the pallete for it's channel. 

-----


> When plotting multi-band imagery using titiler, I use the percentile_2 and percentile_98 as the default vmin and vmax.

The `percentile_*` feature would be a great addition to large_image! Perhaps we should open a feature request there

**Comment by giswqs** [comment]
Thank you for the example. Great to know that it works multi-band imagery. I am implementing a GUI for loading raster in leafmap without coding. 

https://user-images.githubusercontent.com/5016453/148656102-cff398f9-9eeb-4dc2-8974-9a35a2536a8e.mp4
