### ISSUE TITLE
Packaging with pyinstaller

### ISSUE THREAD

**Issue by iiMox** [banesullivan/localtileserver#59]
Hello, I am using the localetileserver, and it is working but when I try to convert my py to exe the program shows me this error.

large_image.exceptions.TileSourceError: No available tilesource for C:\Users\iiMox\AppData\Local\Temp\_MEI50602\NE1_LR_LC_SR_W_DR.tif

**Comment by banesullivan** [comment]
> but when I try to convert my py to exe

You're going to need to provide *a lot more* context here...

I have no experience bundling GDAL (the primary dependency of this package) into packaged environments or executables.

**Comment by banesullivan** [comment]
Please provide more context on how you're creating an exe.

Also please provide a full stack trace and a scooby report: 

```py
import localtileserver
print(localtileserver.Report())
```

**Comment by iiMox** [comment]
Thank you for your response.
Basically, I'm trying to build a localization program that takes images with gpsinfo and try to mark the positions on an offline map. It is working while debugging but the problem in the exe.

I am using auto-py-to-exe to do the render thing I here are the inputs :
pyinstaller --noconfirm --onefile --console --add-data "C:/Users/iiMox/Desktop/Finale/colorbrewer_all_schemes.json;palettable\\colorbrewer\\data\\" --add-data "C:/Users/iiMox/Desktop/Finale/NE1_LR_LC_SR_W_DR.tif;."  "C:/Users/iiMox/Desktop/Finale/program.py"

And here is the result of localtileserver.report() :
`--------------------------------------------------------------------------------
  Date: Tue Jan 11 06:56:22 2022 Romance Standard Time       

                     OS : Windows
                 CPU(s) : 12
                Machine : AMD64
           Architecture : 64bit
                    RAM : 7.9 GiB
            Environment : Python
            File system : unknown

  Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64
  bit (AMD64)]

        localtileserver : 0.4.0
                  flask : 2.0.2
          flask_caching : 1.10.1
            flask_restx : 0.5.1
               requests : 2.26.0
               werkzeug : 2.0.2
                  click : 8.0.3
                 scooby : 0.5.11
            large_image : 1.9.0
large_image_source_gdal : 1.9.0
             cachetools : 5.0.0
                    PIL : 8.4.0
                 psutil : 5.9.0
                  numpy : 1.21.4
             palettable : 3.3.0
                 pyproj : 3.3.0
             osgeo.gdal : 3.4.1
             ipyleaflet : 0.15.0
              traitlets : 5.1.1
                 folium : 0.12.1.post1
--------------------------------------------------------------------------------`

**Comment by banesullivan** [comment]
I think your issue is really in regards to using GDAL with pyinstaller. A quick google revealed this: https://gis.stackexchange.com/a/295584

I don't know if I can be of much help with this... I'm not a Windows user and I've rarely used PyInstaller.

Bundling GDAL like this seems like a big task and this likely won't work if sharing the executable across computers

**Comment by iiMox** [comment]
Can you recommend any other solutions rather than GDAL to perform this idea ?

**Comment by banesullivan** [comment]
GDAL is a core requirement of this package - there is no working around that

**Comment by gtgrp-user** [comment]
Hi @banesullivan, I am having the same issue, but I am not packaging with pyinstaller. I have a notebook where I am using localtileserver to load a satellite image and getting the following error:

`[2022-01-18 16:41:14,725] ERROR in app: Exception on /api/metadata [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask_restx\api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask_restx\resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask_caching\__init__.py", line 475, in decorated_function
    rv = f(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\tileserver\rest.py", line 147, in get
    tile_source = self.get_tile_source()
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\tileserver\rest.py", line 141, in get_tile_source
    return utilities.get_tile_source(filename, projection, style=sty)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\tileserver\utilities.py", line 74, in get_tile_source
    return large_image.open(str(path), projection=projection, style=style, encoding="PNG")
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\large_image\tilesource\__init__.py", line 143, in open
    return getTileSource(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\large_image\tilesource\__init__.py", line 131, in getTileSource
    return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\large_image\tilesource\__init__.py", line 119, in getTileSourceFromDict
    raise TileSourceError('No available tilesource for %s' % pathOrUri)
large_image.exceptions.TileSourceError: No available tilesource for P:\Boliden\Data\014050240020_01\output\20MAR30103630-M2AS-014050240020_01_P001_calibrated_QUAC_byte.tif`

Code used is a follows:

`from localtileserver import get_leaflet_tile_layer, TileClient
# First, create a tile server from local raster file
tile_client = TileClient(image_path)
# Create ipyleaflet tile layer from that server
t = get_leaflet_tile_layer(tile_client)`

And here is the result of localtileserver.report() :
`--------------------------------------------------------------------------------
  Date: Tue Jan 18 16:39:09 2022 GMT Standard Time

                     OS : Windows
                 CPU(s) : 32
                Machine : AMD64
           Architecture : 64bit
                    RAM : 63.9 GiB
            Environment : Jupyter
            File system : unknown

  Python 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:33:54) [MSC
  v.1929 64 bit (AMD64)]

        localtileserver : 0.4.0
                  flask : 2.0.2
          flask_caching : 1.10.1
            flask_restx : 0.5.1
               requests : 2.27.1
               werkzeug : 2.0.1
                  click : 8.0.3
                 scooby : 0.5.11
            large_image : 1.9.0
large_image_source_gdal : 1.9.0
             cachetools : 5.0.0
                    PIL : 8.4.0
                 psutil : 5.9.0
                  numpy : 1.22.0
             palettable : 3.3.0
                 pyproj : 3.3.0
             osgeo.gdal : 3.4.1
             ipyleaflet : 0.15.0
              traitlets : 5.1.1
                shapely : 1.8.0
                 folium : 0.12.1.post1
             matplotlib : 3.5.1`

**Comment by banesullivan** [comment]
@gtgrp-user, would you please open a new issue for this unrelated issue?

**Comment by banesullivan** [comment]
I have no idea how to bundle GDAL with pyinstaller and it's a bit out of scope for this project. Maybe one day, I can come back to this and add a page to the docs on how to do such a thing, but it will be rather involved and different on each OS.

I'm going to close this due to lack of activity and being a bit separate from the scope of this project. If someone else is interested in this, please feel free to revive this issue.
