### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#6]
Thank you for developing this nice package. I just tested it on my computer, and it works like a charm! I plan to incorporate the package into [geemap](https://github.com/giswqs/geemap) and [leafmap](https://github.com/giswqs/leafmap/). Would you consider making the package available on conda-forge? Thanks.

**Comment by giswqs** [comment]
I have been using [xarray-leaflet](https://github.com/davidbrochart/xarray_leaflet) to load local raster datasets to ipyleaflet maps. However, it does not support Windows (see https://github.com/davidbrochart/xarray_leaflet/issues/30) and it is not very stable on Linux. It usually fails to load large raster files. 

Does flask-tileserver support Windows? I have yet to test it on Windows.

**Comment by banesullivan** [comment]
I'd be happy to get this on conda-forge... should be a breeze. Give me a few days as I'd like a little bit of the dust to settle before distributing on conda-forge.


-----

> Does flask-tileserver support Windows? I have yet to test it on Windows.

Assuming you can install GDAL, it should... though I do not use windows so I am unable to test it. There is some hackery going on with launching threads and using the thread IDs to keep track of which raster to serve so this may need to be tested on Windows.

What I can do is implement a Windows runner in GitHub Actions when I get around to #4

**Comment by banesullivan** [comment]
> Does flask-tileserver support Windows? I have yet to test it on Windows.

@giswqs, all should be working on Windows according to the latest CI Tests I have on Windows

**Comment by banesullivan** [comment]
I will have to add `lage_image` to conda-forge before I can add `flask-tileserver` so this may take me a bit

**Comment by giswqs** [comment]
I did test it on Windows, and it works fine. It appears that `large_image` and `large_image_source_gdal` are not available on conda-forge. Let me know if I can be of any help.

**Comment by banesullivan** [comment]
Work in progress here: https://github.com/conda-forge/staged-recipes/pull/17167
