### ISSUE TITLE
Projection and nodata issues with geotiff

### ISSUE THREAD

**Issue by gtgrp-user** [banesullivan/localtileserver#62]
Hi @banesullivan,

Apologies for hijacking someone else's issue. I thought it was related.

I am having the` No available tilesource` issue. To give you the background, I am trying to load a Satellite image on a map using Jupyter Notebook. I am using the following piece of code:
```
from localtileserver import get_leaflet_tile_layer, TileClient
tile_client = TileClient(image_path)
get_leaflet_tile_layer(tile_client)
```
Full stack trace:
> [2022-01-18 16:41:14,725] ERROR in app: Exception on /api/metadata [GET]
> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask\app.py", line 1502, in dispatch_request
>     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask_restx\api.py", line 403, in wrapper
>     resp = resource(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask\views.py", line 84, in view
>     return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask_restx\resource.py", line 49, in dispatch_request
>     resp = meth(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\flask_caching\__init__.py", line 475, in decorated_function
>     rv = f(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\tileserver\rest.py", line 147, in get
>     tile_source = self.get_tile_source()
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\tileserver\rest.py", line 141, in get_tile_source
>     return utilities.get_tile_source(filename, projection, style=sty)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\tileserver\utilities.py", line 74, in get_tile_source
>     return large_image.open(str(path), projection=projection, style=style, encoding="PNG")
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\large_image\tilesource\__init__.py", line 143, in open
>     return getTileSource(*args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\large_image\tilesource\__init__.py", line 131, in getTileSource
>     return getTileSourceFromDict(AvailableTileSources, *args, **kwargs)
>   File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\large_image\tilesource\__init__.py", line 119, in getTileSourceFromDict
>     raise TileSourceError('No available tilesource for %s' % pathOrUri)
> large_image.exceptions.TileSourceError: No available tilesource for P:\Boliden\Data\014050240020_01\output\20MAR30103630-M2AS-014050240020_01_P001_calibrated_QUAC_byte.tif

> ---------------------------------------------------------------------------
> HTTPError                                 Traceback (most recent call last)
> C:\Users\PRITIM~1\AppData\Local\Temp/ipykernel_11608/4220505374.py in <module>
> ----> 1 geo_jsons = display_map(center, image_overlay=rgb_byte, text = "Draw Water/Vagitation ROIs")
> 
> P:\Boliden\notebooks\utils\display_map.py in display_map(center, zoom, image_overlay, text)
>      44         tile_client = TileClient(image_overlay)
>      45         # Create ipyleaflet tile layer from that server
> ---> 46         t = get_leaflet_tile_layer(tile_client)
>      47 
>      48     # Add custom text widget on the map
> 
> C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\widgets.py in get_leaflet_tile_layer(source, port, debug, projection, band, palette, vmin, vmax, nodata, attribution, **kwargs)
>      77         bounds = Union((Tuple(),), default_value=None, allow_none=True).tag(sync=True, o=True)
>      78 
> ---> 79     source, created = get_or_create_tile_client(source, port=port, debug=debug)
>      80     url = source.get_tile_url(
>      81         projection=projection,
> 
> C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\client.py in get_or_create_tile_client(source, port, debug, threaded, processes)
>     348             source.shutdown()
>     349             del source
> --> 350         raise e
>     351     return source, _internally_created
> 
> C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\localtileserver\client.py in get_or_create_tile_client(source, port, debug, threaded, processes)
>     342     try:
>     343         r = requests.get(source.create_url("api/metadata"))
> --> 344         r.raise_for_status()
>     345     except requests.HTTPError as e:
>     346         # Make sure to destroy the server and its thread if internally created.
> 
> C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\requests\models.py in raise_for_status(self)
>     958 
>     959         if http_error_msg:
> --> 960             raise HTTPError(http_error_msg, response=self)
>     961 
>     962     def close(self):
> 
> HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:58429/api/metadata?&filename=P%3A%5CBoliden%5CData%5C014050240020_01%5Coutput%5C20MAR30103630-M2AS-014050240020_01_P001_calibrated_QUAC_byte.tif

localtileserver.report():

>   Date: Tue Jan 18 16:39:09 2022 GMT Standard Time
> 
>                      OS : Windows
>                  CPU(s) : 32
>                 Machine : AMD64
>            Architecture : 64bit
>                     RAM : 63.9 GiB
>             Environment : Jupyter
>             File system : unknown
> 
>            Python 3.10.1 | packaged by conda-forge | (main, Dec 22 2021, 01:33:54) [MSC
>            v.1929 64 bit (AMD64)]
> 
>         localtileserver : 0.4.0
>                   flask : 2.0.2
>           flask_caching : 1.10.1
>             flask_restx : 0.5.1
>                requests : 2.27.1
>                werkzeug : 2.0.1
>                   click : 8.0.3
>                  scooby : 0.5.11
>             large_image : 1.9.0
>             large_image_source_gdal : 1.9.0
>              cachetools : 5.0.0
>                     PIL : 8.4.0
>                  psutil : 5.9.0
>                   numpy : 1.22.0
>              palettable : 3.3.0
>                  pyproj : 3.3.0
>              osgeo.gdal : 3.4.1
>              ipyleaflet : 0.15.0
>               traitlets : 5.1.1
>                 shapely : 1.8.0
>                  folium : 0.12.1.post1
>              matplotlib : 3.5.1

Thanks.

**Comment by banesullivan** [comment]
Hey, @gtgrp-user - the `No available tilesource` error is somewhat of a catch-all error and the real issue could be one of many things.

Would it be possible for you to share the data file `20MAR30103630-M2AS-014050240020_01_P001_calibrated_QUAC_byte.tif` so that I can investigate and reproduce?

**Comment by gtgrp-user** [comment]
Hi @banesullivan,

I have managed to fix "No available tilesource" issue by projecting the input image correctly. However, I have encountered the following issue:
![image_overlay](https://user-images.githubusercontent.com/89073412/150106401-0991dc1d-1829-4816-ad6b-bcbebdaecd53.PNG)

Instead of RGB, I see the above image. RGB image is available [here](https://globaltrust-my.sharepoint.com/:i:/g/personal/pritimoy_podder_globaltrustgrp_com/EeKqodC6SudImngKmw3AgzwBI8Odt4ucLjpW0gE_Kr2zIw?e=oeMEmv) for you to investigate and reproduce the issue.

**Comment by gtgrp-user** [comment]
I have managed to fix this by converting the image to PNG format. However, I have expected the tif format to work!

**Comment by banesullivan** [comment]
>I have managed to fix "No available tilesource" issue by projecting the input image correctly

I'm glad you got the projection fixed and are no able to load the image!

----

The coloring issue is due to the raster missing the `nodata` field. Unfortunately, you may need to recreate the raster because the nodata pixels are filled with `45` in this particular image which is in the middle of the valid data range of `0` to `255` for RGB colors.

You can mostly work around this though by specifying the `nodata` value with `localtileserver`:

```py
from ipyleaflet import Map
from localtileserver import TileClient, get_leaflet_tile_layer

client = TileClient('20MAR30103630-M2AS-014050267010_01_P001_byte.tif')

l = get_leaflet_tile_layer(client, nodata=45, band=[1,2,3])
m = Map(center=client.center())
m.add_layer(l)
m
```
![Screen Shot 2022-01-19 at 8 34 17 AM](https://user-images.githubusercontent.com/22067021/150163166-638b771a-88c5-4f2d-8865-d55fe7bf3d2f.png)

**Comment by gtgrp-user** [comment]
Thanks a lot. It works as you suggested. I really appreciate your time.
