### ISSUE TITLE
Add support for Google Colab

### ISSUE THREAD

**Issue by giswqs** [banesullivan/localtileserver#70]
Now localtileserver is working with JupyterHub. It would be nice to also make it compatible with Colab. The following two lines have no effect on Colab as it is not a JupyterHub. 

```python
import os
os.environ['LOCALTILESERVER_CLIENT_PREFIX'] = f"{os.environ['JUPYTERHUB_SERVICE_PREFIX'].lstrip('/')}/proxy/{{port}}"
```

**Comment by banesullivan** [comment]
@giswqs, it's been a long time since I've used Colab. Could you post a link to a repo and session I could launch to debug this?

**Comment by banesullivan** [comment]
I have no idea how to do this on google colab. It's seemingly not a Jupyter Hub/Lab instance and I have absolutely no idea how to expose a port on the runner. `jupyter-server-proxy` is really the only safe way to do this in cloud environments and I don't think that's possible with google colab

**Comment by banesullivan** [comment]
This is actually really easy! I figured it out while trying to get this to work for PyVista in https://github.com/pyvista/pyvista/issues/3851

I'll see if I can add support directly in `localtileserver`

**Comment by giswqs** [comment]
@banesullivan That's awesome to hear. Can't wait to try it out.

**Comment by banesullivan** [comment]
It's as simple as:

```py
from localtileserver import get_leaflet_tile_layer, examples, TileClient
from ipyleaflet import Map

client = TileClient(examples.get_data_path("bahamas_rgb.tif"))
client.client_host = f'localhost:{client.server.port}'

t = get_leaflet_tile_layer(client)

m = Map(center=client.center(), zoom=client.default_zoom)
m.add_layer(t)
m
```

But I'll make this a little easier in the next release


<img width="1048" alt="Screen Shot 2023-01-29 at 9 01 48 PM" src="https://user-images.githubusercontent.com/22067021/215384880-b3b5aa64-0955-4056-981e-2ce3d8d5dad6.png">

**Comment by giswqs** [comment]
Excited to try this out. Got an error. I should probably wait for the next release. 
![image](https://user-images.githubusercontent.com/5016453/215385723-94d0f090-7c49-40fb-99e4-9343b390b1fb.png)

**Comment by banesullivan** [comment]
yeah... ran into that too... Google Colab installs GDAL and their build is wack (and missing that module). This was handled in afe669cc80c1d29e65e1934956281c85c7935da9 and will be good on the next release

**Comment by banesullivan** [comment]
So, this is fixed by de4d2ef576e3e0c4f0ecaf39bdb044a02747b0cf

What do you think, @giswqs?

```py
from localtileserver import get_leaflet_tile_layer, examples, TileClient
from ipyleaflet import Map

path = examples.get_data_path("bahamas_rgb.tif")

client = TileClient(path)
client.enable_colab()

t = get_leaflet_tile_layer(client)

m = Map(center=client.center(), zoom=client.default_zoom)
m.add_layer(t)
m
```

**Comment by giswqs** [comment]
This gives me hope that localtileserver might work with all major Jupyter notebook platforms, including AWS SageMaker. 

```python
client.client_host = f'localhost:{client.server.port}'
```

**Comment by banesullivan** [comment]
The reason it works is actually pretty specific to colab supporting this `localhost` remapping. Reference https://colab.research.google.com/notebooks/snippets/advanced_outputs.ipynb

> Outputs in the browser can request resources from the kernel by requesting [https://localhost:{port}](https://localhost:%7Bport%7D/). The protocol will automatically be translated from https to http and the localhost will be the kernel executing the code.

**Comment by giswqs** [comment]
You may not need that `client.enable_colab()` explicitly. You might be able to integrate this into `TileClient`.


```python
import sys
if "google.colab" in sys.modules:
  self.client_host = "localhost"
  self.client_port = True
```

**Comment by banesullivan** [comment]
Ah, good point. This assumes `google.clolab` is only ever installed on colab... which is probably a safe assumption

**Comment by giswqs** [comment]
Correct. The `google.colab` module can only be found on Colab. That module can't be found on any other Jupyter platforms or local computers.

**Comment by banesullivan** [comment]
Check out https://colab.research.google.com/drive/1h1iTDl4KqbXxKiyox9eM211vAg6_ONKT?usp=sharing (you have to restart the runtime after installing `localtileserver`)

`0.6.4` now autodetects google colab and all should work

**Comment by giswqs** [comment]
It worked like a charm! Thank you very much for this!
